### ISSUE TITLE
No SRTM_dem_make

### ISSUE THREAD

**Issue by ditafaith** [matthew-gaddes/SRTM-DEM-tools#2]
Hi, 
I activated the tool in my conda env and try to create the DEM base on your page. 
However, I encounter the error, and not really sure, I did't find script with the name `SRTM_dem_make`
(srtm_dem_tools_test) saka@red:~/work/srtm-DEM-tools$ SRTM_dem_make({'west':-4, 'east':-1, 'south':53, 'north':55})
-bash: syntax error near unexpected token `{'west':-4,'

**Comment by matthew-gaddes** [comment]
Hi,

This package is designed to be run from python, not bash.  If you've made an environment successfully, you'd enter something like

 python example.py

 when in the srtm_dem_tools directory.  It's designed to be run from an IDE like spyder, so something like 

spyder example.py 

will allow you to easily customise the script and run it.  I'll close this, but let me know if you have any other issues.

**Comment by ditafaith** [comment]
Hi @matthew-gaddes, thanks for the response.
I ran `python example.py` but getting following error. Is it related missing library or another one ?

> N54W002 : Trying to open locally... Done!
> N54W002 : Creating a mask of water areas... Done!
> 
> Traceback (most recent call last):
>   File "/Users/dita/work/SRTM-DEM-tools/example.py", line 32, in <module>
>     dem_show(dem,lons,lats,title = '1: SRTM3 DEM')                                              # plot the DEM
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Users/dita/work/SRTM-DEM-tools/srtm_dem_tools/plotting.py", line 70, in dem_show
>     f.canvas.set_window_title(title)
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'FigureCanvasMac' object has no attribute 'set_window_title'

Also, is it possible to enter directly the username and password in [this line ](https://github.com/matthew-gaddes/SRTM-DEM-tools/blob/77724127f4bc415f9800b28f6e303a5daf3d3264/example.py#L20C1-L20C1). 
If my understanding correct, what user need is only to change the boundary map in this line to produce DEM map using SRTM3.
`dem, lons, lats =  SRTM_dem_make({'west':-4, 'east':-1, 'south':53, 'north':55},`

**Comment by matthew-gaddes** [comment]
Hi again Saka,

Thanks for spotting that issue.  It's due to a new version of Matplotlib.  If you try the latest commit or version, it should now be fixed: https://github.com/matthew-gaddes/SRTM-DEM-tools/releases/tag/V3.0.1

Re. the username and password.  Yes, you could hard code these into your script rather than be prompted for them each time.  

Re. the boundary map, yes, providing your EarthData details work so you can download new tiles, you could just enter a new bounding box.

**Comment by ditafaith** [comment]
Thanks @matthew-gaddes
I have re-run and there is no error, but where are the results located in?

**Comment by matthew-gaddes** [comment]
You're welcome.  Good question!  They are just left as Matplotlib windows for the user to do as they wish with (e.g. save them).  If you run the example with python example.py you may therefore not see them.  If you run the code with Spyder, this would use ipython, so the figures remain visible even if the code finishes.  I think you could run the example from the shell with something like ipython example.py, but this isn't something I'm familiar with.  

However, I've also just made a new version that saves the figures as pngs: https://github.com/matthew-gaddes/SRTM-DEM-tools/releases/tag/V3.1.0

**Comment by ditafaith** [comment]
Thanks for your great works @matthew-gaddes! It produces several figures.
It seems some data missed
`Unable to open GSHHG_coastlines_2.3.7/GSHHS_shp/f/GSHHS_f_L1.dbf or GSHHG_coastlines_2.3.7/GSHHS_shp/f/GSHHS_f_L1.shp.`

I am not an expert one in Python, just common user actually.
However, in my opinion this tool can make DEM either SRTM1/SRTM3 extremely easier than GIS software, user can execute a simple command (says create_mymaps_srtm1.py) where what we need is to define the user/pass, boundary, and including water body or not. Also, define directory to store the outputs.

**Comment by ditafaith** [comment]
Thanks for your great works @matthew-gaddes! It produces several figures.
It seems some data was missed when I executed `publication_example.py`

_Unable to open GSHHG_coastlines_2.3.7/GSHHS_shp/f/GSHHS_f_L1.dbf or GSHHG_coastlines_2.3.7/GSHHS_shp/f/GSHHS_f_L1.shp._

_PermissionError: [Errno 13] Permission denied: b'/home/matthew/university_work/data/GEBCO_bathymetry/gebco_2021/GEBCO_2021_sub_ice_topo.nc'_

I am not an expert one in Python, just common user actually.
However, in my opinion this tool can help the user to create publication figures either SRTM1 or SRTM3 easier than GIS software, where the user can execute a simple command (says create_mymaps_srtm1.py). What we need is to define the user/pass, boundary, and including water body or not. An option to define the output directory.

**Comment by ditafaith** [comment]
Thanks for your great works @matthew-gaddes! It produces several figures.
It seems some data was missed when I executed `publication_example.py`

_Unable to open GSHHG_coastlines_2.3.7/GSHHS_shp/f/GSHHS_f_L1.dbf or GSHHG_coastlines_2.3.7/GSHHS_shp/f/GSHHS_f_L1.shp.

PermissionError: [Errno 13] Permission denied: b'/home/matthew/university_work/data/GEBCO_bathymetry/gebco_2021/GEBCO_2021_sub_ice_topo.nc'_

I am not an expert one in Python, just common user actually.
However, in my opinion this tool can help the user to create publication figures either SRTM1 or SRTM3 easier than GIS software, where the user can execute a simple command (says create_mymaps_srtm1.py). What we need is to define the user/pass, boundary, and including water body or not. An option to define the output directory.

Why the longitude not changed ?
![1:_SRTM3_DEM](https://github.com/matthew-gaddes/SRTM-DEM-tools/assets/126780178/ab4ba41e-9d01-46be-9144-30fd4ce90425)

**Comment by matthew-gaddes** [comment]
Sorry for missing this last week.  The readme details where you can download all the caostlines (it's too big for a github repo):

Tools for making and manipulating SRTM1 and SRTM3 DEMs. Note that only a small amount of the GSHHS data is included here to give a working example. The full dataset can be downloaded from http://www.soest.hawaii.edu/pwessel/gshhg/

Then you can update the path to where you have saved these and the code should run.  


I'm glad you like it, but I'm afraid I don't understand your questions about longitudes?

**Comment by ditafaith** [comment]
Good to hear from you.
Yes, I already download all the data. However, what I meant is the example you provide. Please check the figures then you can see the longitude not change properly.

**Comment by matthew-gaddes** [comment]
Have you got hte line of code that is making the figure you attached?  I can investigate then.  
Thanks

**Comment by ditafaith** [comment]
If you check [all figures](https://github.com/matthew-gaddes/SRTM-DEM-tools/tree/master/figures), for instance,
`https://github.com/matthew-gaddes/SRTM-DEM-tools/blob/master/figures/4%3A_SRTM3_DEM.png`
Then, the longitude is same, meanwhile only latitude change.
